[package]
name = "miette-sink"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miette = "2.1.2"

# should be a thing
thiserror = "1.0.26"

[dev-dependencies]
log = "0.4.14"
